version: "3.8"
services:
  butlarr:
    image: trimforce/butlarr:latest
    container_name: butlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /umbrel/data/butlarr:/data
      - /umbrel/data/config:/config
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - umbrel_main_network
